/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateTicketRouteImport } from './routes/create-ticket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketHistoryTsxRouteImport } from './routes/ticket-history.tsx'

const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTicketRoute = CreateTicketRouteImport.update({
  id: '/create-ticket',
  path: '/create-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketHistoryTsxRoute = TicketHistoryTsxRouteImport.update({
  id: '/ticket-history/tsx',
  path: '/ticket-history/tsx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-ticket': typeof CreateTicketRoute
  '/dashboard': typeof DashboardRoute
  '/ticket': typeof TicketRoute
  '/ticket-history/tsx': typeof TicketHistoryTsxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-ticket': typeof CreateTicketRoute
  '/dashboard': typeof DashboardRoute
  '/ticket': typeof TicketRoute
  '/ticket-history/tsx': typeof TicketHistoryTsxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-ticket': typeof CreateTicketRoute
  '/dashboard': typeof DashboardRoute
  '/ticket': typeof TicketRoute
  '/ticket-history/tsx': typeof TicketHistoryTsxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-ticket'
    | '/dashboard'
    | '/ticket'
    | '/ticket-history/tsx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-ticket' | '/dashboard' | '/ticket' | '/ticket-history/tsx'
  id:
    | '__root__'
    | '/'
    | '/create-ticket'
    | '/dashboard'
    | '/ticket'
    | '/ticket-history/tsx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTicketRoute: typeof CreateTicketRoute
  DashboardRoute: typeof DashboardRoute
  TicketRoute: typeof TicketRoute
  TicketHistoryTsxRoute: typeof TicketHistoryTsxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-ticket': {
      id: '/create-ticket'
      path: '/create-ticket'
      fullPath: '/create-ticket'
      preLoaderRoute: typeof CreateTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-history/tsx': {
      id: '/ticket-history/tsx'
      path: '/ticket-history/tsx'
      fullPath: '/ticket-history/tsx'
      preLoaderRoute: typeof TicketHistoryTsxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTicketRoute: CreateTicketRoute,
  DashboardRoute: DashboardRoute,
  TicketRoute: TicketRoute,
  TicketHistoryTsxRoute: TicketHistoryTsxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
