/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../routes/__root";
import { Route as CreateTicketRouteImport } from "../routes/create-ticket";

const CreateTicketRoute = CreateTicketRouteImport.update({
	id: "/createTicket",
	path: "/createTicket",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/createTicket": typeof CreateTicketRoute;
}
export interface FileRoutesByTo {
	"/createTicket": typeof CreateTicketRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/createTicket": typeof CreateTicketRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/createTicket";
	fileRoutesByTo: FileRoutesByTo;
	to: "/createTicket";
	id: "__root__" | "/createTicket";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	CreateTicketRoute: typeof CreateTicketRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/createTicket": {
			id: "/createTicket";
			path: "/createTicket";
			fullPath: "/createTicket";
			preLoaderRoute: typeof CreateTicketRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	CreateTicketRoute: CreateTicketRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
